name: Validate Database Schema

on:
  push:
    branches: [main, develop]
    paths:
      - 'migrations/**'
      - 'schema.json'
      - 'lib/database.types.ts'
  pull_request:
    branches: [main, develop]
    paths:
      - 'migrations/**'
      - 'schema.json'
      - 'lib/database.types.ts'
  workflow_dispatch:

jobs:
  validate-schema:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Validate schema
        run: npm run db:validate
        env:
          NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
      
      - name: Generate database types
        run: npm run db:types
        env:
          NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
      
      - name: Check for changes in database.types.ts
        id: git-check
        run: |
          git diff --exit-code --quiet lib/database.types.ts || echo "::set-output name=changed::true"
      
      - name: Create Pull Request if types changed
        if: steps.git-check.outputs.changed == 'true' && github.event_name != 'pull_request'
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: 'chore: Update database type definitions'
          title: 'chore: Update database type definitions'
          body: |
            This PR updates the database type definitions based on schema changes.
            
            Generated automatically by the validate-schema GitHub Actions workflow.
          branch: update-database-types
          base: ${{ github.ref }} 